services:
  app:  # Define the 'app' service for the Next.js application
    container_name: ${CONTAINER_NAME}  # Set the container name using the environment variable CONTAINER_NAME
    build:  # Build the Docker image using the specified Dockerfile
      context: ..  # Set the build context to the parent directory to access the Dockerfile in the root directory
      dockerfile: Dockerfile.nextjs  # Specify the Dockerfile to use for building the image
      args:
        NODE_ENV: ${NODE_ENV}  # Pass the value of NODE_ENV as a build argument to the Dockerfile
    ports:
      - ${PORT}  # Map a port on the host to a port inside the container
    env_file:
      - ${ENV_FILE}  # Load the environment variables from the specified .env file
    volumes:
      - ..:/usr/src/app  # Mount the current directory (parent directory) into the container at /usr/src/app
      - /usr/src/app/node_modules  # Create an anonymous volume for node_modules to persist dependencies
    command: npm run dev  # Command to start the application in development mode (using npm run dev)