services:
  nginx:  # Defines the NGINX reverse proxy service for handling HTTPS requests
    container_name: ${NGINX_CONTAINER_NAME}  # Sets the container name from environment variable (e.g., jorge-portfolio-frontend-nginx-dev-server-container)
    build:
      context: ../  # Set the build context to the nginx directory
      dockerfile: docker/nginx/Dockerfile.nginx  # Specify the Dockerfile to use for building Nginx
      args:
        ENV_TYPE: ${ENV_TYPE}  # Pass the ENV_TYPE argument to specify the environment type (e.g., dev, qa, prod)
        NGINX_CONF_DIR: ${NGINX_CONF_DIR}  # Pass the NGINX_CONF argument to the build process
        NGINX_CERTS_DIR: ${NGINX_CERTS_DIR}  # Pass the CERTS_DIR argument to the build process
    image: ${NGINX_IMAGE_NAME}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"  # Map port 443 on the host to port 443 inside the container
    depends_on:
      - frontend  # Ensure that Nginx starts after the Next.js app