# Dockerfile for Nginx
FROM nginx:latest

ARG NGINX_CONF_DIR
ARG NGINX_CERTS_DIR
ARG ENV_TYPE

# Copy the configuration file to the container based on the environment type
COPY ${NGINX_CONF_DIR} /etc/nginx/conf.d/default.conf

# Copy the corresponding certificates to the container
COPY ${NGINX_CERTS_DIR} /etc/nginx/certs/${ENV_TYPE}