services:
  nginx:  # Define the Nginx service
    image: nginx:latest  # Use the latest version of the official Nginx image
    container_name: ${NGINX_CONTAINER_NAME}  # Name of the Nginx container
    build:
      context: ../../  # Set the build context to the nginx directory
      dockerfile: docker/nginx/Dockerfile.nginx  # Specify the Dockerfile to use for building Nginx
      args:
        NGINX_CONF: ${NGINX_CONF}  # Pass the NGINX_CONF argument to the build process
        CERTS_DIR: ${CERTS_DIR}  # Pass the CERTS_DIR argument to the build process
        ENV_TYPE: ${ENV_TYPE}  # Pass the ENV_TYPE argument to specify the environment type (e.g., dev, qa, prod)
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"  # Map port 443 on the host to port 443 inside the container
    depends_on:
      - app  # Ensure that Nginx starts after the Next.js app