name: CD-Workflow

# This CD (Continuous Deployment) workflow is triggered by another workflow using `workflow_call`.
on:
  workflow_call:
    inputs:
      deploy_branch:
        required: true
        type: string
    secrets:
      # DEV environment
      SERVER_SSH_KEY_DEV:      { required: true }
      ENV_VARS_DEV_CD:         { required: true }
      # QA environment
      SERVER_SSH_KEY_QA:       { required: true }
      ENV_VARS_QA_CD:          { required: true }
      # PROD environment
      SERVER_SSH_KEY_PROD:     { required: true }
      ENV_VARS_PROD_CD:        { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment branch variable
        id: vars
        run: echo "DEPLOY_BRANCH=${{ inputs.deploy_branch }}" >> $GITHUB_ENV

      - name: Extract server connection info
        run: |
          if [[ "${{ inputs.deploy_branch }}" == "dev" ]]; then
            echo "${{ secrets.ENV_VARS_DEV_CD }}" > env.temp
          elif [[ "${{ inputs.deploy_branch }}" == "qa" ]]; then
            echo "${{ secrets.ENV_VARS_QA_CD }}" > env.temp
          elif [[ "${{ inputs.deploy_branch }}" == "main" ]]; then
            echo "${{ secrets.ENV_VARS_PROD_CD }}" > env.temp
          fi

          # Obtain SERVER_IP y SERVER_USER y export as env
          export $(grep -E '^(SERVER_IP|SERVER_USER)=' env.temp | xargs)
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          echo "SERVER_USER=$SERVER_USER" >> $GITHUB_ENV

      - name: Pull latest code and create .env file in remote server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ inputs.deploy_branch == 'dev' && secrets.SERVER_SSH_KEY_DEV || 
                  inputs.deploy_branch == 'qa' && secrets.SERVER_SSH_KEY_QA || 
                  inputs.deploy_branch == 'main' && secrets.SERVER_SSH_KEY_PROD }}
          port: 22
          script: |
            DEPLOY_BRANCH="${{ inputs.deploy_branch }}"

            cd /var/www/jorge-nextjs-portfolio/
            git pull origin $DEPLOY_BRANCH

            mkdir -p env/$DEPLOY_BRANCH
            echo -e "${{ 
              inputs.deploy_branch == 'dev' && secrets.ENV_VARS_DEV_CD || 
              inputs.deploy_branch == 'qa' && secrets.ENV_VARS_QA_CD || 
              inputs.deploy_branch == 'main' && secrets.ENV_VARS_PROD_CD 
            }}" > env/$DEPLOY_BRANCH/cd.env

      - name: Run Makefile to lift containers on remote
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ inputs.deploy_branch == 'dev' && secrets.SERVER_SSH_KEY_DEV || 
                  inputs.deploy_branch == 'qa' && secrets.SERVER_SSH_KEY_QA || 
                  inputs.deploy_branch == 'main' && secrets.SERVER_SSH_KEY_PROD }}
          port: 22
          script: |
            DEPLOY_BRANCH="${{ inputs.deploy_branch }}"
            cd /var/www/jorge-nextjs-portfolio

            set -a
            source env/$DEPLOY_BRANCH/cd.env
            set +a

            make ${DEPLOY_BRANCH}-server-build-up