name: CI-Workflow

# Trigger the workflow on push events to the specified branches
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2 # Check out the repository code
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Add Docker Compose installation
      - name: Set environment variables based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            mkdir -p env/dev
            echo "NODE_ENV=${{ secrets.NODE_ENV_DEV }}" >> env/dev/.env.dev.server
            echo "NEXT_PORT=${{ secrets.NEXT_PORT_DEV }}" >> env/dev/.env.dev.server
            echo "HOST_PORT=${{ secrets.HOST_PORT_DEV }}" >> env/dev/.env.dev.server
            echo "NEXT_CONTAINER_NAME=${{ secrets.NEXT_CONTAINER_NAME_DEV }}" >> env/dev/.env.dev.server
            echo "INSTALL_PLAYWRIGHT=${{ secrets.INSTALL_PLAYWRIGHT_DEV }}" >> env/dev/.env.dev.server
            echo "INSTALL_DEV_LIBRARIES=${{ secrets.INSTALL_DEV_LIBRARIES_DEV }}" >> env/dev/.env.dev.server
            echo "IMAGE_NAME=${{ secrets.IMAGE_NAME_DEV }}" >> env/dev/.env.dev.server
            echo "ENV_FILE_NAME=${{ secrets.ENV_FILE_NAME_DEV }}" >> env/dev/.env.dev.server
            echo "START_COMMAND=${{ secrets.START_COMMAND_DEV }}" >> env/dev/.env.dev.server
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            mkdir -p env/qa
            echo "NODE_ENV=${{ secrets.NODE_ENV_QA }}" >> env/qa/.env.qa.server
            echo "NEXT_PORT=${{ secrets.NEXT_PORT_QA }}" >> env/qa/.env.qa.server
            echo "HOST_PORT=${{ secrets.HOST_PORT_QA }}" >> env/qa/.env.qa.server
            echo "NEXT_CONTAINER_NAME=${{ secrets.NEXT_CONTAINER_NAME_QA }}" >> env/qa/.env.qa.server
            echo "INSTALL_PLAYWRIGHT=${{ secrets.INSTALL_PLAYWRIGHT_QA }}" >> env/qa/.env.qa.server
            echo "INSTALL_DEV_LIBRARIES=${{ secrets.INSTALL_DEV_LIBRARIES_QA }}" >> env/qa/.env.qa.server
            echo "IMAGE_NAME=${{ secrets.IMAGE_NAME_QA }}" >> env/qa/.env.qa.server
            echo "ENV_FILE_NAME=${{ secrets.ENV_FILE_NAME_QA }}" >> env/qa/.env.qa.server
            echo "START_COMMAND=${{ secrets.START_COMMAND_QA }}" >> env/qa/.env.qa.server
            echo "USE_VOLUMES=${{ secrets.USE_VOLUMES_QA }}" >> env/qa/.env.qa.server
            echo "USE_VOLUMES_NODE_MODULES=${{ secrets.USE_VOLUMES_NODE_MODULES_QA }}" >> env/qa/.env.qa.server
            echo "USE_PORTS=${{ secrets.USE_PORTS_QA }}" >> env/qa/.env.qa.server
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            mkdir -p env/prod
            echo "NODE_ENV=${{ secrets.NODE_ENV_PROD }}" >> env/prod/.env.prod.server
            echo "NEXT_PORT=${{ secrets.NEXT_PORT_PROD }}" >> env/prod/.env.prod.server
            echo "HOST_PORT=${{ secrets.HOST_PORT_PROD }}" >> env/prod/.env.prod.server
            echo "NEXT_CONTAINER_NAME=${{ secrets.NEXT_CONTAINER_NAME_PROD }}" >> env/prod/.env.prod.server
            echo "INSTALL_PLAYWRIGHT=${{ secrets.INSTALL_PLAYWRIGHT_PROD }}" >> env/prod/.env.prod.server
            echo "INSTALL_DEV_LIBRARIES=${{ secrets.INSTALL_DEV_LIBRARIES_PROD }}" >> env/prod/.env.prod.server
            echo "IMAGE_NAME=${{ secrets.IMAGE_NAME_PROD }}" >> env/prod/.env.prod.server
            echo "ENV_FILE_NAME=${{ secrets.ENV_FILE_NAME_PROD }}" >> env/prod/.env.prod.server
            echo "START_COMMAND=${{ secrets.START_COMMAND_PROD }}" >> env/prod/.env.prod.server
            echo "USE_VOLUMES=${{ secrets.USE_VOLUMES_PROD }}" >> env/prod/.env.prod.server
            echo "USE_VOLUMES_NODE_MODULES=${{ secrets.USE_VOLUMES_NODE_MODULES_PROD }}" >> env/prod/.env.prod.server
            echo "USE_PORTS=${{ secrets.USE_PORTS_PROD }}" >> env/prod/.env.prod.server
          else
            mkdir -p env/feature
            echo "NODE_ENV=${{ secrets.NODE_ENV_FEATURE }}" >> env/feature/.env.feature.local
            echo "NEXT_PORT=${{ secrets.NEXT_PORT_FEATURE }}" >> env/feature/.env.feature.local
            echo "HOST_PORT=${{ secrets.HOST_PORT_FEATURE }}" >> env/feature/.env.feature.local
            echo "NEXT_CONTAINER_NAME=${{ secrets.NEXT_CONTAINER_NAME_FEATURE }}" >> env/feature/.env.feature.local
            echo "INSTALL_PLAYWRIGHT=${{ secrets.INSTALL_PLAYWRIGHT_FEATURE }}" >> env/feature/.env.feature.local
            echo "INSTALL_DEV_LIBRARIES=${{ secrets.INSTALL_DEV_LIBRARIES_FEATURE }}" >> env/feature/.env.feature.local
            echo "IMAGE_NAME=${{ secrets.IMAGE_NAME_FEATURE }}" >> env/feature/.env.feature.local
            echo "ENV_FILE_NAME=${{ secrets.ENV_FILE_NAME_FEATURE }}" >> env/feature/.env.feature.local
            echo "START_COMMAND=${{ secrets.START_COMMAND_FEATURE }}" >> env/feature/.env.feature.local
            echo "USE_VOLUMES=${{ secrets.USE_VOLUMES_FEATURE }}" >> env/feature/.env.feature.local
            echo "USE_VOLUMES_NODE_MODULES=${{ secrets.USE_VOLUMES_NODE_MODULES_FEATURE }}" >> env/feature/.env.feature.local
            echo "USE_PORTS=${{ secrets.USE_PORTS_FEATURE }}" >> env/feature/.env.feature.local
          fi
      - name: Set up Docker Compose and run container
        run: |
          echo "Branch: ${{ github.ref }}"  # Print the current GitHub reference (branch) to verify its value
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then  # If the branch is 'dev'
            docker-compose --env-file env/dev/.env.dev.server -p jorge-portfolio-frontend-dev-server -f docker/docker-compose.yaml -f docker/docker-compose-override-ci.yaml up -d --build  # Use the dev Docker Compose file to start the container
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then  # If the branch is 'qa'
            docker-compose --env-file env/qa/.env.qa.server -p jorge-portfolio-frontend-qa-server -f docker/docker-compose.yaml -f docker/docker-compose-override-ci.yaml up -d --build  # Use the qa Docker Compose file to start the container
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then  # If the branch is 'main'
            docker-compose --env-file env/prod/.env.prod.server -p jorge-portfolio-frontend-prod-server -f docker/docker-compose.yaml -f docker/docker-compose-override-ci.yaml up -d --build  # Use the prod Docker Compose file to start the container
          else  # If it's a feature branch or any other branch
            docker-compose --env-file env/feature/.env.feature.local -p jorge-portfolio-frontend-feature-local -f docker/docker-compose.yaml -f docker/docker-compose-override-feature.yaml up -d --build  # Use the feature Docker Compose file to start the container
          fi
      - name: Install dependencies in Docker container
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker-compose --env-file env/dev/.env.dev.server -p jorge-portfolio-frontend-dev-server -f docker/docker-compose.yaml exec -T frontend sh -c 'export NODE_ENV=development && npm install --only=dev --legacy-peer-deps'
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            docker-compose --env-file env/qa/.env.qa.server -p jorge-portfolio-frontend-qa-server -f docker/docker-compose.yaml exec -T frontend sh -c 'export NODE_ENV=development && npm install --only=dev --legacy-peer-deps'
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker-compose --env-file env/prod/.env.prod.server -p jorge-portfolio-frontend-prod-server -f docker/docker-compose.yaml exec -T frontend sh -c 'export NODE_ENV=development'
          else
            echo "Skipping installation in non-dev, non-qa, and non-prod branches."
          fi
      - name: Run ESLint in Docker
        # Use dev or local docker-compose file depending on the branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" || "${{ github.ref }}" =~ refs/heads/feature/.* ]]; then
            # If the branch is dev or feature/*
            if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
              docker-compose --env-file env/dev/.env.dev.server -p jorge-portfolio-frontend-dev-server -f docker/docker-compose.yaml exec -T frontend npm run lint
            else
              docker-compose --env-file env/feature/.env.feature.local -p jorge-portfolio-frontend-feature-local -f docker/docker-compose.yaml exec -T frontend npm run lint
            fi
          else
            echo "Skipping ESLint in non-dev and non-feature branches."
          fi
      - name: Run Jest in Docker
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker-compose --env-file env/dev/.env.dev.server -p jorge-portfolio-frontend-dev-server -f docker/docker-compose.yaml exec -T frontend npm test
          else
            echo "Skipping Jest tests for branch ${{ github.ref }} as tests are only run on the 'dev' branch"
          fi
      - name: Run Playwright in Docker
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker-compose --env-file env/dev/.env.dev.server -p jorge-portfolio-frontend-dev-server -f docker/docker-compose.yaml exec -T frontend npx playwright test
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            docker-compose --env-file env/qa/.env.qa.server -p jorge-portfolio-frontend-qa-server -f docker/docker-compose.yaml exec -T frontend npx playwright test
          else
            echo "Skipping Playwright tests for branch ${{ github.ref }} as tests are only run on the 'dev' and 'qa' branch."
          fi
      - name: Stop and Remove Docker Containers
        run: |
          # Stop and remove containers based on the branch
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker-compose --env-file env/dev/.env.dev.server -f docker/docker-compose.yaml down
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            docker-compose --env-file env/qa/.env.qa.server -f docker/docker-compose.qa.yaml down
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker-compose --env-file env/prod/.env.prod.server -f docker/docker-compose.prod.yaml down
          else
            docker-compose --env-file env/feature/.env.feature.local -f docker/docker-compose.yaml down
          fi